
server:
  port: 8080

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@192.168.70.140:1521:orcl
    username: client
    password: client

    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 300000
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 300000
      connection-test-query: SELECT 1 FROM dual

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl